/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package movietheatremgmtsys;
import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author ADMIN
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        USERNAME = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setPreferredSize(new java.awt.Dimension(50, 30));
        label1.setText(" WELCOME");
        getContentPane().add(label1);
        label1.setBounds(0, 0, 90, 20);

        label2.setText("NAME :");
        getContentPane().add(label2);
        label2.setBounds(50, 50, 43, 20);

        USERNAME.setText("USERNAME");
        getContentPane().add(USERNAME);
        USERNAME.setBounds(50, 90, 71, 20);

        label4.setText("PASSWORD");
        getContentPane().add(label4);
        label4.setBounds(50, 130, 73, 20);

        label5.setText("PHONE_NUMBER");
        getContentPane().add(label5);
        label5.setBounds(50, 210, 106, 20);

        label6.setText("EMAIL_ADDRESS");
        getContentPane().add(label6);
        label6.setBounds(50, 170, 103, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 50, 130, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 90, 130, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 210, 130, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 170, 130, 20);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(220, 130, 130, 20);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 240, 110, 23);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 240, 120, 23);

        jButton3.setText("Already registered?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 270, 127, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel1.setText("Register Here");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 4, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{  
Class.forName("com.mysql.jdbc.Driver");  
  int flag=0;
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/MOVIE_MGMT","root","root");  

PreparedStatement stmt=con.prepareStatement("insert into USERINFO (name,username,password,email,contact_number)values(?,?,?,?,?)");  
String nm=jTextField2.getText();
if(!nm.matches("[a-zA-Z]+")||nm==null)
               //WRONG THING BOX
{final JPanel panel = new JPanel();

    JOptionPane.showMessageDialog(panel, "Name cannot be empty or have numbers"
            + " or special characters!", "Warning",JOptionPane.ERROR_MESSAGE);
    
}
else{   
    
String uname=jTextField3.getText();
if(uname==null)
{
final JPanel panel = new JPanel();

    JOptionPane.showMessageDialog(panel, "No data entered", "Warning",JOptionPane.ERROR_MESSAGE);
}
else{
   String checkSql = "select count(*) from userinfo where username = '"+uname+"'";

Statement st = con.createStatement();
ResultSet result = st.executeQuery(checkSql);
result.next();
if ( (result.getInt(1) == 1)) {
final JPanel panel = new JPanel();

    JOptionPane.showMessageDialog(panel, "Username already exists!", "Warning",JOptionPane.ERROR_MESSAGE);

} 
    else{
    
    
String pwd=jPasswordField1.getText();
if(pwd.length()<8){
        final JPanel panel = new JPanel();
    JOptionPane.showMessageDialog(panel, "Password must be atleast "
            + "8 characters!", "Warning",JOptionPane.ERROR_MESSAGE);}
else{
String eid=jTextField6.getText();
if(eid==null)
{
    final JPanel panel = new JPanel();

    JOptionPane.showMessageDialog(panel, "No data entered", "Warning",JOptionPane.ERROR_MESSAGE);
}
else{
String pno=jTextField5.getText();
if(pno.length()!=10||!(pno.matches("-?\\d+(\\.\\d+)?")))
{
    final JPanel panel = new JPanel();

    JOptionPane.showMessageDialog(panel, "Invalid number!", "Warning",JOptionPane.ERROR_MESSAGE);
}

else{
stmt.setString(1,nm);//1 specifies the first parameter in the query  
stmt.setString(2,uname);  
stmt.setString(3,pwd);  
stmt.setString(4,eid);  
stmt.setString(5,pno);  
  
int i=stmt.executeUpdate();  
System.out.println(i+" records inserted");  
  
  
con.close(); 

TicketSelection ts= new TicketSelection();
ts.setVisible(true);
this.dispose();
} 
}}}}}}catch(Exception e){ System.out.println(e);}  



      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AlreadyRegUser aru= new AlreadyRegUser();
        aru.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label USERNAME;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
